version: '3.8'

services:
  mariadb:
    image: mariadb:10.4
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_DATABASE: 'kotlinblog'
      MYSQL_USER : 'admin'
      MYSQL_PASSWORD: 'admin123'
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
      #- ./init:/docker-entrypoint-initdb.d
    networks:
      - mariadb_network
networks:
  mariadb_network:
    driver: bridge

