

server:
  port: 9000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  datasource:
    username: admin
    password: admin123
    url: jdbc:mariadb://127.0.0.1:3306/kotlinblog?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        hibernate.default_batch_fetch_size: 1000
        globally_quoted_identifiers: true
    show-sql: true

decorator:
  datasource:
    p6spy:
      enable-logging: true